package igu;

import java.awt.Image;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.util.Hashtable;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.Conversor;
import logica.JComboBoxRender;

/**
 *
 * @author user
 */
public class Menu extends javax.swing.JFrame {

    Conversor conversor = new Conversor();
    
    Hashtable<Object, ImageIcon> mElementos;
    int width = 20;
    int height = 20;
    
    private String logo_sol = "/icons/peru.png";
    private String logo_dolar = "/icons/estados-unidos-de-america.png";
    private String logo_UE = "/icons/union-europea.png";
    private String logo_libraE = "/icons/reino-unido.png";
    private String logo_yen = "/icons/japon.png";
    private String logo_won = "/icons/corea-del-sur.png";

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        Icon currencyIcon = new ImageIcon(new ImageIcon(getClass().getResource("/icons/cambio-de-divisas.png")).getImage()
                .getScaledInstance(IconCurrencyD.getWidth(), IconCurrencyD.getHeight(), 0));
        IconCurrencyD.setIcon(currencyIcon);
        
        Icon temperatureIcon = new ImageIcon(new ImageIcon(getClass().getResource("/icons/termometro.png")).getImage()
                .getScaledInstance(IconTemperatureT.getWidth(), IconTemperatureT.getHeight(), 0));
        IconTemperatureT.setIcon(temperatureIcon);
        
        Icon distanceIcon = new ImageIcon(new ImageIcon(getClass().getResource("/icons/distanciamiento-social.png")).getImage()
                .getScaledInstance(IconDistanceD.getWidth(), IconDistanceD.getHeight(), 0));
        IconDistanceD.setIcon(distanceIcon);
        
        mElementos = new Hashtable<>();

        //Cargando cbo de divisas
        agregarElemento("Sol", getIcono(logo_sol));
        agregarElemento("Dólar", getIcono(logo_dolar));
        agregarElemento("Euro", getIcono(logo_UE));
        agregarElemento("Libra Esterlina", getIcono(logo_libraE));
        agregarElemento("Yen Japones", getIcono(logo_yen));
        agregarElemento("Won sul-coreano", getIcono(logo_won));
        
        String[] valoresCboDivisa = conversor.valoresDivisas();
        cboDeDivisa.removeAllItems();
        cboADivisa.removeAllItems();
        for (int i = 0; i < valoresCboDivisa.length; i++) {
            String element = valoresCboDivisa[i];
            cboDeDivisa.addItem(element);
            cboADivisa.addItem(element);
        }
        
        JComboBoxRender mJComboBoxRender = new JComboBoxRender(mElementos);
        cboDeDivisa.setRenderer(mJComboBoxRender);
        cboADivisa.setRenderer(mJComboBoxRender);
        
        //Cargando cbo de temperatura
        String[] valoresCboTemperatura = conversor.valoresTemperatura();
        cboDeTemp.removeAllItems();
        cboATemp.removeAllItems();
        for (int i = 0; i < valoresCboTemperatura.length; i++) {
            String element = valoresCboTemperatura[i];
            cboDeTemp.addItem(element);
            cboATemp.addItem(element);
        }
        
        //Cargando cbo de distancia
        String[] valoresCboDeDistancia = conversor.valoresDistancia();
        cboDeDistancia.removeAllItems();
        cboADistancia.removeAllItems();
        for (int i = 0; i < valoresCboDeDistancia.length; i++) {
            String element = valoresCboDeDistancia[i];
            cboDeDistancia.addItem(element);
            cboADistancia.addItem(element);
        }

        setIconImage(getIconImage());
    }
    
    @Override
    public Image getIconImage() {
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("icons/monedas.png"));
        return retvalue;
    }
    
    public void agregarElemento(String akey, ImageIcon aImageIcon) {
        mElementos.put(akey, aImageIcon);
    }

    public ImageIcon getIcono(String path) {
        return new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage()
                .getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCurrency = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCantidadDivisa = new javax.swing.JTextField();
        btnConvertirDivisa = new javax.swing.JButton();
        lblResultadoDivisa = new javax.swing.JLabel();
        cboDeDivisa = new javax.swing.JComboBox<>();
        cboADivisa = new javax.swing.JComboBox<>();
        btnLimpiarDivisas = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        IconCurrencyD = new javax.swing.JLabel();
        jPanelTemperature = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantidadTemp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboDeTemp = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboATemp = new javax.swing.JComboBox<>();
        btnConvertirTemp = new javax.swing.JButton();
        lblResultadoTemp = new javax.swing.JLabel();
        btnLimpiarT = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        IconTemperatureT = new javax.swing.JLabel();
        jPanelDistance = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLongitusDist = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cboDeDistancia = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cboADistancia = new javax.swing.JComboBox<>();
        btnConvertirDistan = new javax.swing.JButton();
        lblResultadoDistan = new javax.swing.JLabel();
        btnLimpiarDistancia = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        IconDistanceD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 21, 21));

        jTabbedPane1.setBackground(new java.awt.Color(21, 21, 21));
        jTabbedPane1.setForeground(new java.awt.Color(255, 246, 224));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(276, 511));

        jPanelCurrency.setBackground(new java.awt.Color(21, 21, 21));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 246, 224));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Divisas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 246, 224));
        jLabel2.setText("Cantidad:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 246, 224));
        jLabel3.setText("De:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 246, 224));
        jLabel4.setText("A:");

        txtCantidadDivisa.setBackground(new java.awt.Color(21, 21, 21));
        txtCantidadDivisa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCantidadDivisa.setForeground(new java.awt.Color(255, 246, 224));
        txtCantidadDivisa.setBorder(null);

        btnConvertirDivisa.setBackground(new java.awt.Color(21, 21, 21));
        btnConvertirDivisa.setForeground(new java.awt.Color(255, 246, 224));
        btnConvertirDivisa.setText("Convertir");
        btnConvertirDivisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirDivisaActionPerformed(evt);
            }
        });

        lblResultadoDivisa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblResultadoDivisa.setForeground(new java.awt.Color(255, 246, 224));

        cboDeDivisa.setBackground(new java.awt.Color(21, 21, 21));
        cboDeDivisa.setForeground(new java.awt.Color(255, 246, 224));
        cboDeDivisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDeDivisa.setBorder(null);

        cboADivisa.setBackground(new java.awt.Color(21, 21, 21));
        cboADivisa.setForeground(new java.awt.Color(255, 246, 224));
        cboADivisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboADivisa.setBorder(null);

        btnLimpiarDivisas.setBackground(new java.awt.Color(21, 21, 21));
        btnLimpiarDivisas.setForeground(new java.awt.Color(255, 246, 224));
        btnLimpiarDivisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/borrar.png"))); // NOI18N
        btnLimpiarDivisas.setBorder(null);
        btnLimpiarDivisas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarDivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDivisasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCurrencyLayout = new javax.swing.GroupLayout(jPanelCurrency);
        jPanelCurrency.setLayout(jPanelCurrencyLayout);
        jPanelCurrencyLayout.setHorizontalGroup(
            jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                                    .addComponent(btnConvertirDivisa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblResultadoDivisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                                    .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCantidadDivisa)
                                        .addComponent(cboDeDivisa, 0, 171, Short.MAX_VALUE)
                                        .addComponent(cboADivisa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator2))))
                            .addComponent(btnLimpiarDivisas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(IconCurrencyD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCurrencyLayout.setVerticalGroup(
            jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(txtCantidadDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCurrencyLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCurrencyLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboDeDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboADivisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanelCurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConvertirDivisa, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lblResultadoDivisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnLimpiarDivisas)
                .addGap(59, 59, 59)
                .addComponent(IconCurrencyD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Divisas", jPanelCurrency);

        jPanelTemperature.setBackground(new java.awt.Color(21, 21, 21));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 246, 224));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Temperatura");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 246, 224));
        jLabel6.setText("Cantidad:");

        txtCantidadTemp.setBackground(new java.awt.Color(21, 21, 21));
        txtCantidadTemp.setForeground(new java.awt.Color(255, 246, 224));
        txtCantidadTemp.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 246, 224));
        jLabel7.setText("De:");

        cboDeTemp.setBackground(new java.awt.Color(21, 21, 21));
        cboDeTemp.setForeground(new java.awt.Color(255, 246, 224));
        cboDeTemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDeTemp.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 246, 224));
        jLabel8.setText("A:");

        cboATemp.setBackground(new java.awt.Color(21, 21, 21));
        cboATemp.setForeground(new java.awt.Color(255, 246, 224));
        cboATemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboATemp.setBorder(null);

        btnConvertirTemp.setBackground(new java.awt.Color(21, 21, 21));
        btnConvertirTemp.setForeground(new java.awt.Color(255, 246, 224));
        btnConvertirTemp.setText("Convertir");
        btnConvertirTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirTempActionPerformed(evt);
            }
        });

        lblResultadoTemp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblResultadoTemp.setForeground(new java.awt.Color(255, 246, 224));

        btnLimpiarT.setBackground(new java.awt.Color(21, 21, 21));
        btnLimpiarT.setForeground(new java.awt.Color(255, 246, 224));
        btnLimpiarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/borrar.png"))); // NOI18N
        btnLimpiarT.setBorder(null);
        btnLimpiarT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTemperatureLayout = new javax.swing.GroupLayout(jPanelTemperature);
        jPanelTemperature.setLayout(jPanelTemperatureLayout);
        jPanelTemperatureLayout.setHorizontalGroup(
            jPanelTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTemperatureLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jPanelTemperatureLayout.createSequentialGroup()
                .addGroup(jPanelTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTemperatureLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTemperatureLayout.createSequentialGroup()
                                .addGroup(jPanelTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnLimpiarT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnConvertirTemp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultadoTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTemperatureLayout.createSequentialGroup()
                                .addGroup(jPanelTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator12)
                                    .addComponent(jSeparator11)
                                    .addComponent(jSeparator9)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCantidadTemp)
                                    .addComponent(cboDeTemp, 0, 170, Short.MAX_VALUE)
                                    .addComponent(cboATemp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator10)))))
                    .addGroup(jPanelTemperatureLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(IconTemperatureT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTemperatureLayout.setVerticalGroup(
            jPanelTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTemperatureLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanelTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(txtCantidadTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(cboDeTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(cboATemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanelTemperatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConvertirTemp)
                    .addComponent(lblResultadoTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnLimpiarT)
                .addGap(72, 72, 72)
                .addComponent(IconTemperatureT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Temperatura", jPanelTemperature);

        jPanelDistance.setBackground(new java.awt.Color(21, 21, 21));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 246, 224));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Distancia");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 246, 224));
        jLabel10.setText("Longitud:");

        txtLongitusDist.setBackground(new java.awt.Color(21, 21, 21));
        txtLongitusDist.setForeground(new java.awt.Color(255, 246, 224));
        txtLongitusDist.setBorder(null);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 246, 224));
        jLabel11.setText("De:");

        cboDeDistancia.setBackground(new java.awt.Color(21, 21, 21));
        cboDeDistancia.setForeground(new java.awt.Color(255, 246, 224));
        cboDeDistancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDeDistancia.setBorder(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 246, 224));
        jLabel12.setText("A:");

        cboADistancia.setBackground(new java.awt.Color(21, 21, 21));
        cboADistancia.setForeground(new java.awt.Color(255, 246, 224));
        cboADistancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboADistancia.setBorder(null);

        btnConvertirDistan.setBackground(new java.awt.Color(21, 21, 21));
        btnConvertirDistan.setForeground(new java.awt.Color(255, 246, 224));
        btnConvertirDistan.setText("Convertir");
        btnConvertirDistan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirDistanActionPerformed(evt);
            }
        });

        lblResultadoDistan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblResultadoDistan.setForeground(new java.awt.Color(255, 246, 224));

        btnLimpiarDistancia.setBackground(new java.awt.Color(21, 21, 21));
        btnLimpiarDistancia.setForeground(new java.awt.Color(255, 246, 224));
        btnLimpiarDistancia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/borrar.png"))); // NOI18N
        btnLimpiarDistancia.setBorder(null);
        btnLimpiarDistancia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDistanciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDistanceLayout = new javax.swing.GroupLayout(jPanelDistance);
        jPanelDistance.setLayout(jPanelDistanceLayout);
        jPanelDistanceLayout.setHorizontalGroup(
            jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistanceLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelDistanceLayout.createSequentialGroup()
                .addGroup(jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDistanceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDistanceLayout.createSequentialGroup()
                                .addGroup(jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLimpiarDistancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnConvertirDistan))
                                .addGap(18, 18, 18)
                                .addComponent(lblResultadoDistan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDistanceLayout.createSequentialGroup()
                                .addGroup(jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cboADistancia, javax.swing.GroupLayout.Alignment.LEADING, 0, 166, Short.MAX_VALUE)
                                    .addComponent(cboDeDistancia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtLongitusDist, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6)))))
                    .addGroup(jPanelDistanceLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(IconDistanceD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDistanceLayout.setVerticalGroup(
            jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDistanceLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(txtLongitusDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(cboDeDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(cboADistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDistanceLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConvertirDistan))
                    .addGroup(jPanelDistanceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblResultadoDistan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(btnLimpiarDistancia)
                .addGap(87, 87, 87)
                .addComponent(IconDistanceD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Distancia", jPanelDistance);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirDivisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirDivisaActionPerformed
        try {
            double cantidad = Double.parseDouble(txtCantidadDivisa.getText());
            int monNatal = cboDeDivisa.getSelectedIndex();
            int monDestino = cboADivisa.getSelectedIndex();

            BigDecimal valorConvertido = conversor.Divisas(cantidad, monNatal, monDestino);
            lblResultadoDivisa.setText(valorConvertido + "");
        } catch (AssertionError e) {
            //Manejo de Error si es que queremos mostrarlo tal como es
            /*String mensajeError = "Error: " + e.getClass().getName() + ": " + e.getMessage();
            JOptionPane.showMessageDialog(null, mensajeError, "Error", JOptionPane.ERROR_MESSAGE);*/
            JOptionPane.showMessageDialog(null, "Debe seleccionar un item valido en las DIVISAS", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            //Manejo de Error si es que queremos mostrarlo tal como es
            /*String mensajeError = "Error: " + e.getClass().getName() + ": " + e.getMessage();
            JOptionPane.showMessageDialog(null, mensajeError, "Error", JOptionPane.ERROR_MESSAGE);*/
            JOptionPane.showMessageDialog(null, "Debe ingresar una cantidad a convertir", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConvertirDivisaActionPerformed

    private void btnLimpiarDivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDivisasActionPerformed
        txtCantidadDivisa.setText("");
        cboDeDivisa.setSelectedIndex(0);
        cboADivisa.setSelectedIndex(0);
        lblResultadoDivisa.setText("");
    }//GEN-LAST:event_btnLimpiarDivisasActionPerformed

    private void btnLimpiarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTActionPerformed
        txtCantidadTemp.setText("");
        cboDeTemp.setSelectedIndex(0);
        cboATemp.setSelectedIndex(0);
        lblResultadoTemp.setText("");
    }//GEN-LAST:event_btnLimpiarTActionPerformed

    private void btnLimpiarDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDistanciaActionPerformed
        txtLongitusDist.setText("");
        cboDeDistancia.setSelectedIndex(0);
        cboADistancia.setSelectedIndex(0);
        lblResultadoDistan.setText("");
    }//GEN-LAST:event_btnLimpiarDistanciaActionPerformed

    private void btnConvertirTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirTempActionPerformed
        try {
            double cantidad = Double.parseDouble(txtCantidadTemp.getText());
            int escalaOrigen = cboDeTemp.getSelectedIndex();
            int escalaDestino = cboATemp.getSelectedIndex();

            BigDecimal valorConvertido = conversor.Temperatura(cantidad, escalaOrigen, escalaDestino);
            lblResultadoTemp.setText(valorConvertido + "");
        } catch (AssertionError e) {
            //Manejo de Error si es que queremos mostrarlo tal como es
            /*String mensajeError = "Error: " + e.getClass().getName() + ": " + e.getMessage();
            JOptionPane.showMessageDialog(null, mensajeError, "Error", JOptionPane.ERROR_MESSAGE);*/
            JOptionPane.showMessageDialog(null, "Debe seleccionar un item valido en las TEMPERATURAS", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            //Manejo de Error si es que queremos mostrarlo tal como es
            /*String mensajeError = "Error: " + e.getClass().getName() + ": " + e.getMessage();
            JOptionPane.showMessageDialog(null, mensajeError, "Error", JOptionPane.ERROR_MESSAGE);*/
            JOptionPane.showMessageDialog(null, "Debe ingresar una cantidad a convertir", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConvertirTempActionPerformed

    private void btnConvertirDistanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirDistanActionPerformed
        try {
            double cantidad = Double.parseDouble(txtLongitusDist.getText());
            int distanciaOrigen = cboDeDistancia.getSelectedIndex();
            int distanciaDestino = cboADistancia.getSelectedIndex();

            BigDecimal valorConvertido = conversor.distancia(cantidad, distanciaOrigen, distanciaDestino);
            lblResultadoDistan.setText(valorConvertido + "");
        } catch (AssertionError e) {
            //Manejo de Error si es que queremos mostrarlo tal como es
            /*String mensajeError = "Error: " + e.getClass().getName() + ": " + e.getMessage();
            JOptionPane.showMessageDialog(null, mensajeError, "Error", JOptionPane.ERROR_MESSAGE);*/
            JOptionPane.showMessageDialog(null, "Debe seleccionar un item valido en las LONGITUDES", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            //Manejo de Error si es que queremos mostrarlo tal como es
            /*String mensajeError = "Error: " + e.getClass().getName() + ": " + e.getMessage();
            JOptionPane.showMessageDialog(null, mensajeError, "Error", JOptionPane.ERROR_MESSAGE);*/
            JOptionPane.showMessageDialog(null, "Debe ingresar una cantidad a convertir", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConvertirDistanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconCurrencyD;
    private javax.swing.JLabel IconDistanceD;
    private javax.swing.JLabel IconTemperatureT;
    private javax.swing.JButton btnConvertirDistan;
    private javax.swing.JButton btnConvertirDivisa;
    private javax.swing.JButton btnConvertirTemp;
    private javax.swing.JButton btnLimpiarDistancia;
    private javax.swing.JButton btnLimpiarDivisas;
    private javax.swing.JButton btnLimpiarT;
    private javax.swing.JComboBox<String> cboADistancia;
    private javax.swing.JComboBox<String> cboADivisa;
    private javax.swing.JComboBox<String> cboATemp;
    private javax.swing.JComboBox<String> cboDeDistancia;
    private javax.swing.JComboBox<String> cboDeDivisa;
    private javax.swing.JComboBox<String> cboDeTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCurrency;
    private javax.swing.JPanel jPanelDistance;
    private javax.swing.JPanel jPanelTemperature;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblResultadoDistan;
    private javax.swing.JLabel lblResultadoDivisa;
    private javax.swing.JLabel lblResultadoTemp;
    private javax.swing.JTextField txtCantidadDivisa;
    private javax.swing.JTextField txtCantidadTemp;
    private javax.swing.JTextField txtLongitusDist;
    // End of variables declaration//GEN-END:variables
}
